Resolve protobuf version issue for kinesis client

diff --git a/bin/spark-shell b/bin/spark-shell
--- a/bin/spark-shell
+++ b/bin/spark-shell
@@ -33,36 +33,39 @@ install_app() {
   local local_tarball="${_DIR}/$2"
   local binary="${_DIR}/$3"
 
-  # setup `curl` and `wget` silent options if we're running on Jenkins
-  local curl_opts="-L"
-  local wget_opts=""
-  if [ -n "$AMPLAB_JENKINS" ]; then
-    curl_opts="-s ${curl_opts}"
-    wget_opts="--quiet ${wget_opts}"
-  else
-    curl_opts="--progress-bar ${curl_opts}"
-    wget_opts="--progress=bar:force ${wget_opts}"
-  fi
-
   if [ -z "$3" -o ! -f "$binary" ]; then
-    # check if we already have the tarball
-    # check if we have curl installed
-    # download application
-    [ ! -f "${local_tarball}" ] && [ $(command -v curl) ] && \
-      echo "exec: curl ${curl_opts} ${remote_tarball}" 1>&2 && \
-      curl ${curl_opts} "${remote_tarball}" > "${local_tarball}"
-    # if the file still doesn't exist, lets try `wget` and cross our fingers
-    [ ! -f "${local_tarball}" ] && [ $(command -v wget) ] && \
-      echo "exec: wget ${wget_opts} ${remote_tarball}" 1>&2 && \
-      wget ${wget_opts} -O "${local_tarball}" "${remote_tarball}"
-    # if both were unsuccessful, exit
-    [ ! -f "${local_tarball}" ] && \
-      echo -n "ERROR: Cannot download $2 with cURL or wget; " && \
-      echo "please install manually and try again." && \
-      exit 2
+    download_app "${remote_tarball}" "${local_tarball}"
     cd "${_DIR}" && tar -xzf "$2"
     rm -rf "$local_tarball"
   fi
+}
+
+# Download any application given a URL
+## Arg1 - Remote URL
+## Arg2 - Local file name
+download_app() {
+  local remote_url="$1"
+  local local_name="$2"
+
+  # setup `curl` and `wget` options
+  local curl_opts="--progress-bar -L"
+  local wget_opts="--progress=bar:force"
+
+  # check if we already have the given application
+  # check if we have curl installed
+  # download application
+  [ ! -f "${local_name}" ] && [ $(command -v curl) ] && \
+    echo "exec: curl ${curl_opts} ${remote_url}" 1>&2 && \
+    curl ${curl_opts} "${remote_url}" > "${local_name}"
+  # if the file still doesn't exist, lets try `wget` and cross our fingers
+  [ ! -f "${local_name}" ] && [ $(command -v wget) ] && \
+    echo "exec: wget ${wget_opts} ${remote_url}" 1>&2 && \
+    wget ${wget_opts} -O "${local_name}" "${remote_url}"
+  # if both were unsuccessful, exit
+  [ ! -f "${local_name}" ] && \
+    echo -n "ERROR: Cannot download $2 with cURL or wget; " && \
+    echo "please install manually and try again." && \
+    exit 2
 }
 
 # Determine the Spark version from the root pom.xml file and
@@ -70,6 +73,7 @@ install_app() {
 install_spark() {
   local SPARK_VERSION=`grep "<spark.version>" "${_DIR}/../pom.xml" | head -n1 | awk -F '[<>]' '{print $3}'`
   local HADOOP_VERSION=`grep "<hadoop.version>" "${_DIR}/../pom.xml" | head -n1 | awk -F '[<>]' '{print $3}'`
+  local SPARK_DIR="${_DIR}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}"
   local APACHE_MIRROR=${APACHE_MIRROR:-'http://d3kbcqa49mib13.cloudfront.net'}
 
   install_app \
@@ -77,7 +81,25 @@ install_spark() {
     "spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz" \
     "spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}/bin/spark-shell"
 
-  SPARK_BIN="${_DIR}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}/bin/spark-shell"
+  # Check and resolve a protobuf version issue;
+  # aws-kinesis-client-1.7+ requires protobuf-java-2.6+ though, spark-2.0.x depends on protobuf-java-2.5.
+  local PROTOBUF_VERSION=`grep "<protobuf.version>" "${_DIR}/../pom.xml" | head -n1 | awk -F '[<>]' '{print $3}'`
+  local PROTOBUF_DETECTED_BIN=`ls ${SPARK_DIR}/jars | grep -E 'protobuf-java-[0-9\.]*\.jar'`
+  local PROTOBUF_DETECTED_VERSION=`echo ${PROTOBUF_DETECTED_BIN} | awk 'match($0, /[0-9]+\.[0-9]+\.[0-9]+/) {print substr($0, RSTART, RLENGTH)}'`
+  # See simple version normalization: http://stackoverflow.com/questions/16989598/bash-comparing-version-numbers
+  function version { echo "$@" | awk -F. '{ printf("%03d%03d%03d\n", $1,$2,$3); }'; }
+  if [ $(version $PROTOBUF_DETECTED_VERSION) -lt $(version $PROTOBUF_VERSION) ]; then
+    local MAVEN_CENTRAL_URL="http://central.maven.org/maven2"
+    local PROTOBUF_BIN="protobuf-java-${PROTOBUF_VERSION}.jar"
+    local PROTOBUF_URL="${MAVEN_CENTRAL_URL}/com/google/protobuf/protobuf-java/${PROTOBUF_VERSION}/${PROTOBUF_BIN}"
+
+    echo "Replacing ${PROTOBUF_DETECTED_BIN} with ${PROTOBUF_BIN} to resolve a kinesis client protobuf dependency" 1>&2
+
+    download_app "${PROTOBUF_URL}" "${PROTOBUF_BIN}"
+    rm "${SPARK_DIR}/jars/${PROTOBUF_DETECTED_BIN}" && mv "${PROTOBUF_BIN}" "${SPARK_DIR}/jars/"
+  fi
+
+  SPARK_BIN="${SPARK_DIR}/bin/spark-shell"
 }
 
 # Install the proper version of Spark for launching spark-shell
